### ISSUE TITLE
basemap install does not work through pip

### ISSUE THREAD

**Issue by d-val** [pieqq/PyGeoIpMap#12]
you can either do it through conda by 
`conda install -c https://conda.anaconda.org/anaconda basemap`
or if in ubuntu through 
`sudo apt-get install python-mpltoolkits.basemap`

**Comment by mrquincle** [comment]
Python3: `sudo apt install python3-mpltoolkits.basemap`

**Comment by veox** [comment]
For ref, upstream issue: https://github.com/matplotlib/basemap/issues/251

In short: looks like the package is too big to be on PyPI.

It can still be installed, e.g., with `pip install [-e] <URI-of-release-tarball>`.

**Comment by veox** [comment]
See PR #17 for a `requirements.txt` that works for me.
