### ISSUE TITLE
Use geoip2 instead of GeoIP

### ISSUE THREAD

**Issue by ZombieNinjaPirate** [pieqq/PyGeoIpMap#9]
Thanks for a very useful script :)

I was wondering if its possible to add support for  geoip2 or use it as a replacement for GeoIP?
Using geoip2.database one would be able to use the GeoLite2-City.mmdb database which has better accuracy.

**Comment by pierrrrrrre** [comment]
Yes it looks like a good idea!

I'll check this later. If you have time you can do it yourself and propose a merge request as well.

**Comment by Trustmega** [comment]
Solved by https://github.com/pieqq/PyGeoIpMap/pull/21
